// <auto-generated />
using EmployeeDataLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDataLib.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20220703160901_update-migration")]
    partial class updatemigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeDataLib.Entities.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"), 1L, 1);

                    b.Property<string>("EmpAddress")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("EmpEmail")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("EmpName")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EmpPhone")
                        .HasColumnType("char(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("Varchar(20)");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
